# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  blazorshorturl:
    image: blazorshorturl
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=$APP_ENVIRONMENT
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=$APP_FORWARD_HEADERS
      # - ASPNETCORE_URLS=$BASE_ADDRESS
      - ASPNETCORE_PORT=$APP_SERVER_PORT
      - BUILD_PLATFORM=$APP_PLATFORM
      - AppDbContext=$AppDbContext
      - DataContext=$DataContext
      - ADMIN_EMAIL=$ADMIN_EMAIL
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - API_KEY=$API_KEY
    ports:
      - $APP_SERVER_PORT:$APP_SERVER_PORT
