# compose.yaml
#
# Please refer https://aka.ms/HTTPSinContainer on how to setup
# an https developer certificate for your ASP.NET Core service.

services:
  blazorshorturl:
    image: blazorshorturl
    build:
      context: .
      dockerfile: ./Dockerfile
    # env_file: .env
    ports:
      - 8080:8080
    environment:
      - BUILD_PLATFORM=${APP_PLATFORM}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=${ASPNETCORE_FORWARDEDHEADERS_ENABLED}
      # - ASPNETCORE_HTTP_PORTS=$ASPNETCORE_HTTP_PORTS
      # - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - AppDbContext=${AppDbContext}
      - DataContext=${DataContext}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - API_KEY=${API_KEY}
      - APP_UID:${APP_UID}
      - BASE_ADDRESS=${BASE_ADDRESS}
      - LOG_LEVEL:${LOG_LEVEL}

# volumes:
#   - /opt/BlazorShortUrl/logs:/logs

# networks:
#   default:
#     name: dockhand
#     external: true
