FROM mcr.microsoft.com/dotnet/core/sdk:9.0 AS build
WORKDIR /src

# copy csproj and restore as distinct layers
COPY BlazorShortUrl.sln .
COPY BlazorShortUrl.csproj ./
RUN dotnet restore -r linux-x64

# copy everything else and build app
COPY . ./
WORKDIR /src
RUN dotnet publish -c release -o /app -r linux-x64 --self-contained false --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["./aspnetapp"]